version: "3.1"

services:
    beties:
      depends_on:
        - dataBase
        - messageBroker
      build: ./betIES
      ports: 
        - "2020:8000"
      volumes:
        - ../betIES/var/www/html/
        - ../betIES/src/main/java/com/project/ua/betIES/repository/*
      links:
        - dataBase
      networks:
        - default
      restart: on-failure
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://dataBase:3306/betIES",
          "spring.datasource.username" : "beties",
          "spring.datasource.password" : "projeto.1",
          "spring.datasource.driver-class-name" : "com.mysql.jdbc.Driver",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "create",
          "server.port": 8000,
          "spring.rabbitmq.username" : "beties",
          "spring.rabbitmq.password" : "beties",
          "spring.rabbitmq.host" : "messageBroker",
          "spring.rabbitmq.port" : 5672
         }'
    dataBase:
        image: mysql:8.0
        ports: 
            - "3334:3334"
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
        environment:
            MYSQL_DATABASE: betIES
            MYSQL_USER: beties
            MYSQL_ROOT_PASSWORD: projeto.1
            MYSQL_PASSWORD: projeto.1
        volumes:
            - ./dataBase:/var/lib/mysql
        networks:
            - default
        restart: always
    
    messageBroker:
      image: rabbitmq:3.8-management-alpine
      environment:
          - RABBITMQ_DEFAULT_USER=beties
          - RABBITMQ_DEFAULT_PASS=beties
      ports:
          - "5672:5672"
